### PR TITLE
Shorter salt, SHA1 and hashed password as binary

### PR DESCRIPTION
**Pull request by afronski**
I have added support for shorter salt (*4 characters*), support for *SHA1* signing algorithm with tests and ability to format the result of `hash_password/3` as a raw binary.

Longer explanation why:

I am creating a new application which needs to be backward-compatible with older system, which uses *PBKDF2*, but with much shorter salt (default is 4), SHA1 and different formatting scheme (it uses *RFC2307* from *LDAP*). In order to not clutter this library with such arcane scheme, I would love to add the necessary parts which allow me to use `comeonin` with `pbkdf2_elixir` and the rest from `hex.pm`.

@riverrun I would totally understand if you will ditch the _PR_, as it introduces old-fashioned stuff. Waiting for your suggestions.

### CODE REVIEW

**Comment by riverrun** [comment]
Thanks for the contribution. Let me think about these changes, and then I will get back to you soon.

**Comment by riverrun** [comment]
A quick update - I am working on updating Comeonin to version 5 (and pbkdf2_elixir to version 1) at the moment. That should be ready soon, and then I can look at these changes afterwards. I will probably add these changes while making it clear that they are legacy options.

**Comment by afronski** [comment]
If there is anything I can help with here @riverrun do not hesitate to ask. :wink:

**Comment by riverrun** [comment]
Could you show me an example of the hash format you need? (the tests do not seem to be correct - that's why I am asking)

**Comment by afronski** [comment]
@riverrun I did not introduce a new format on purpose to not clutter the library.

The only thing I needed was `:raw`, which returns a raw binary, and I could construct any format from that.

**Comment by riverrun** [comment]
Ok. Are you using Plug in your app?

**Comment by afronski** [comment]
Yup. I know about the workaround for _SHA1_, the problem is I do not see any easy way to use it later with `comeonin` in that way.

**Comment by riverrun** [comment]
Here is an example of what you can do with [Plug and Comeonin](https://github.com/riverrun/legacy_pbkdf2). The `lib/legacy_pbkdf2.ex` file gives you an example of a module that you could add to your app.

I still have not decided where to go with this issue. I might add the changes you suggested to this library, I might just add an example script (based on the `lib/legacy_pbkdf2.ex` file) to the Comeonin wiki, or I might release `legacy_pbkdf2` (with some minor alterations) as a separate hex package.

If you have any comments / questions, please let me know.

**Comment by afronski** [comment]
@riverrun Thanks, I will wait for your decision then, and I will play with the workaround.

**Comment by riverrun** [comment]
I have added a guide to the Comeonin wiki about creating custom implementations here - https://github.com/riverrun/comeonin/wiki/Implementing-Comeonin-behaviours

I plan on leaving the legacy_pbkdf2 app as it is (just as an example).

**Pull request closed without merging**
